//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepfreezeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepfreezeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Deepfreeze.io for Windows.
        /// </summary>
        internal static string AboutButtonTooltip {
            get {
                return ResourceManager.GetString("AboutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepfreeze.io Account.
        /// </summary>
        internal static string ActiveUserHeader {
            get {
                return ResourceManager.GetString("ActiveUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title for your new Archive..
        /// </summary>
        internal static string ArchiveTitleHelperText {
            get {
                return ResourceManager.GetString("ArchiveTitleHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating total archive size....
        /// </summary>
        internal static string CalculatingTotalArchiveSizeText {
            get {
                return ResourceManager.GetString("CalculatingTotalArchiveSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic check and installation of updates, every time the About page is opened..
        /// </summary>
        internal static string CheckForUpdateAutomaticText {
            get {
                return ResourceManager.GetString("CheckForUpdateAutomaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string CheckForUpdateText {
            get {
                return ResourceManager.GetString("CheckForUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for application updates and install them..
        /// </summary>
        internal static string CheckForUpdateTooltip {
            get {
                return ResourceManager.GetString("CheckForUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or choose a folder.
        /// </summary>
        internal static string ChooseFolderText {
            get {
                return ResourceManager.GetString("ChooseFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was successfully frozen..
        /// </summary>
        internal static string CompletedNotificationText {
            get {
                return ResourceManager.GetString("CompletedNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectButtonContent {
            get {
                return ResourceManager.GetString("ConnectButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to your Deepfreeze.io Account.
        /// </summary>
        internal static string ConnectHeaderText {
            get {
                return ResourceManager.GetString("ConnectHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection lost. Pausing active uploads....
        /// </summary>
        internal static string ConnectionLostMessage {
            get {
                return ResourceManager.GetString("ConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection restored. Resuming auto-paused uploads....
        /// </summary>
        internal static string ConnectionRestoredMessage {
            get {
                return ResourceManager.GetString("ConnectionRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new archive.
        /// </summary>
        internal static string CreatingArchiveText {
            get {
                return ResourceManager.GetString("CreatingArchiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log.
        /// </summary>
        internal static string DebugButtonContent {
            get {
                return ResourceManager.GetString("DebugButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re experiencing problems with Deepfreeze.io for Windows, we might ask you to provide a copy of the log. Clicking the button saves the log file on your Desktop as &quot;DFLog.txt&quot;..
        /// </summary>
        internal static string DebugHelpText {
            get {
                return ResourceManager.GetString("DebugHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete the archive using the Deepfreeze.io website Dashboard..
        /// </summary>
        internal static string DeleteArchiveFromDashboardGenericText {
            get {
                return ResourceManager.GetString("DeleteArchiveFromDashboardGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonContent {
            get {
                return ResourceManager.GetString("DeleteButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DisconnectButtonContent {
            get {
                return ResourceManager.GetString("DisconnectButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files here to start uploading a new archive.
        /// </summary>
        internal static string DragAndDropText {
            get {
                return ResourceManager.GetString("DragAndDropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected is empty..
        /// </summary>
        internal static string EmptyFolderSelection {
            get {
                return ResourceManager.GetString("EmptyFolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error adding your file(s) for upload..
        /// </summary>
        internal static string ErrorAddingFilesGenericText {
            get {
                return ResourceManager.GetString("ErrorAddingFilesGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error calculating the total upload progress..
        /// </summary>
        internal static string ErrorCalculatingS3UploadSizeText {
            get {
                return ResourceManager.GetString("ErrorCalculatingS3UploadSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t check for updates without an active Internet connection..
        /// </summary>
        internal static string ErrorCheckingForUpdateWithoutInternetGenericText {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdateWithoutInternetGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading your folder for upload..
        /// </summary>
        internal static string ErrorChoosingFolderGenericText {
            get {
                return ResourceManager.GetString("ErrorChoosingFolderGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to connect your account..
        /// </summary>
        internal static string ErrorConnectingGenericText {
            get {
                return ResourceManager.GetString("ErrorConnectingGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect your account without an active Internet connection..
        /// </summary>
        internal static string ErrorConnectingWithoutInternetText {
            get {
                return ResourceManager.GetString("ErrorConnectingWithoutInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while creating your archive..
        /// </summary>
        internal static string ErrorCreatingArchiveGenericText {
            get {
                return ResourceManager.GetString("ErrorCreatingArchiveGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while creating your upload..
        /// </summary>
        internal static string ErrorCreatingUploadGenericText {
            get {
                return ResourceManager.GetString("ErrorCreatingUploadGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while deleting your upload..
        /// </summary>
        internal static string ErrorDeletingUploadGenericText {
            get {
                return ResourceManager.GetString("ErrorDeletingUploadGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version of Deepfreeze.io for Windows cannot be downloaded at this time..
        /// </summary>
        internal static string ErrorDownloadingUpdateGenericText {
            get {
                return ResourceManager.GetString("ErrorDownloadingUpdateGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while initializing your uploads..
        /// </summary>
        internal static string ErrorInitializingClientUploadsListGenericText {
            get {
                return ResourceManager.GetString("ErrorInitializingClientUploadsListGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while initializing the application..
        /// </summary>
        internal static string ErrorInitializingShellViewModelGenericText {
            get {
                return ResourceManager.GetString("ErrorInitializingShellViewModelGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check for a new version of Deepfreeze.io for Windows. Please reinstall the application..
        /// </summary>
        internal static string ErrorInvalidDeploymentExceptionGenericText {
            get {
                return ResourceManager.GetString("ErrorInvalidDeploymentExceptionGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application cannot be updated. It is likely not a ClickOnce application..
        /// </summary>
        internal static string ErrorInvalidOperationCheckingForUpdateGenericText {
            get {
                return ResourceManager.GetString("ErrorInvalidOperationCheckingForUpdateGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while preparing your upload..
        /// </summary>
        internal static string ErrorPreparingUploadGenericText {
            get {
                return ResourceManager.GetString("ErrorPreparingUploadGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while checking your upload&apos;s progress..
        /// </summary>
        internal static string ErrorRefreshingProgressGenericText {
            get {
                return ResourceManager.GetString("ErrorRefreshingProgressGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while refreshing your account&apos;s information..
        /// </summary>
        internal static string ErrorRefreshingUserStatsGenericText {
            get {
                return ResourceManager.GetString("ErrorRefreshingUserStatsGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while removing your upload from the application..
        /// </summary>
        internal static string ErrorRemovingUploadGenericText {
            get {
                return ResourceManager.GetString("ErrorRemovingUploadGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with your upload..
        /// </summary>
        internal static string ErrorUploadingGenericText {
            get {
                return ResourceManager.GetString("ErrorUploadingGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitHeader {
            get {
                return ResourceManager.GetString("ExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.deepfreeze.io/o/password_reset/.
        /// </summary>
        internal static string ForgotPasswordURL {
            get {
                return ResourceManager.GetString("ForgotPasswordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Free / .
        /// </summary>
        internal static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepfreeze.io will remain minimized in the tray notification area. To close it, right click the tray icon and select &quot;Exit&quot;..
        /// </summary>
        internal static string MinimizedMessageText {
            get {
                return ResourceManager.GetString("MinimizedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection found. Please ensure you are connected to a network with Internet access..
        /// </summary>
        internal static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any pending uploads from this app..
        /// </summary>
        internal static string NoUploadsHeaderText {
            get {
                return ResourceManager.GetString("NoUploadsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your password..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordTextboxHelper {
            get {
                return ResourceManager.GetString("PasswordTextboxHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseButtonContent {
            get {
                return ResourceManager.GetString("PauseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of .
        /// </summary>
        internal static string PercentageOfText {
            get {
                return ResourceManager.GetString("PercentageOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string PreferencesHeader {
            get {
                return ResourceManager.GetString("PreferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string QuotaHeader {
            get {
                return ResourceManager.GetString("QuotaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveButtonContent {
            get {
                return ResourceManager.GetString("RemoveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Restart for changes to take effect..
        /// </summary>
        internal static string RestartNeededText {
            get {
                return ResourceManager.GetString("RestartNeededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string ResumeButtonContent {
            get {
                return ResourceManager.GetString("ResumeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t know your password?.
        /// </summary>
        internal static string SetPasswordText {
            get {
                return ResourceManager.GetString("SetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.deepfreeze.io/account/.
        /// </summary>
        internal static string SetPasswordURL {
            get {
                return ResourceManager.GetString("SetPasswordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string StatusCompletedText {
            get {
                return ResourceManager.GetString("StatusCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error freezing Archive.
        /// </summary>
        internal static string StatusErrorNotificationText {
            get {
                return ResourceManager.GetString("StatusErrorNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StatusErrorText {
            get {
                return ResourceManager.GetString("StatusErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string StatusPausedText {
            get {
                return ResourceManager.GetString("StatusPausedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string StatusPendingText {
            get {
                return ResourceManager.GetString("StatusPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string StatusUploadedText {
            get {
                return ResourceManager.GetString("StatusUploadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        internal static string StatusUploadingText {
            get {
                return ResourceManager.GetString("StatusUploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Archive Size: .
        /// </summary>
        internal static string TotalArchiveSizeText {
            get {
                return ResourceManager.GetString("TotalArchiveSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Archives: .
        /// </summary>
        internal static string TotalArchivesText {
            get {
                return ResourceManager.GetString("TotalArchivesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total.
        /// </summary>
        internal static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Uploads: .
        /// </summary>
        internal static string TotalUploadsText {
            get {
                return ResourceManager.GetString("TotalUploadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate. Please enter your Deepfreeze.io account credentials..
        /// </summary>
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButtonContent {
            get {
                return ResourceManager.GetString("UploadButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was successfully uploaded..
        /// </summary>
        internal static string UploadedNotificationText {
            get {
                return ResourceManager.GetString("UploadedNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepfreeze.io for Windows is up to date..
        /// </summary>
        internal static string UpToDateText {
            get {
                return ResourceManager.GetString("UpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Used / .
        /// </summary>
        internal static string UsedText {
            get {
                return ResourceManager.GetString("UsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your email..
        /// </summary>
        internal static string UsernameError {
            get {
                return ResourceManager.GetString("UsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someone@example.com.
        /// </summary>
        internal static string UsernameTextboxHelper {
            get {
                return ResourceManager.GetString("UsernameTextboxHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionHeaderText {
            get {
                return ResourceManager.GetString("VersionHeaderText", resourceCulture);
            }
        }
    }
}
