//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepfreezeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepfreezeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepfreeze Account.
        /// </summary>
        internal static string ActiveUserHeader {
            get {
                return ResourceManager.GetString("ActiveUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Free / .
        /// </summary>
        internal static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonContent {
            get {
                return ResourceManager.GetString("LoginButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutButtonContent {
            get {
                return ResourceManager.GetString("LogoutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your password..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordTextboxHelper {
            get {
                return ResourceManager.GetString("PasswordTextboxHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string PreferencesHeader {
            get {
                return ResourceManager.GetString("PreferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string QuotaHeader {
            get {
                return ResourceManager.GetString("QuotaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stage.deepfreeze.io/o/password_reset/.
        /// </summary>
        internal static string RememberPasswordURL {
            get {
                return ResourceManager.GetString("RememberPasswordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Archives: .
        /// </summary>
        internal static string TotalArchivesText {
            get {
                return ResourceManager.GetString("TotalArchivesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total.
        /// </summary>
        internal static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate. Please enter your Deepfreeze account credentials..
        /// </summary>
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Used / .
        /// </summary>
        internal static string UsedText {
            get {
                return ResourceManager.GetString("UsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your email..
        /// </summary>
        internal static string UsernameError {
            get {
                return ResourceManager.GetString("UsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someone@example.com.
        /// </summary>
        internal static string UsernameTextboxHelper {
            get {
                return ResourceManager.GetString("UsernameTextboxHelper", resourceCulture);
            }
        }
    }
}
