// BigStashExt.idl : IDL source for BigStashExt
//

// This file will be processed by the MIDL tool to
// produce the type library (BigStashExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(06FD2AA3-4C3F-4722-BE95-758317E5D86B),
	version(1.0),
]
library BigStashExtLib
{
	importlib("stdole2.tlb");
};

